- name: MariaDB
  hosts: all
  #-var: 
    #maria_contrasena: M1asix@1
    #wp_contrasena: M1asix@1
  tasks:
    - name: instalar mariadb
      apt:
        name:
          - mariadb-server
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
        
    - name: isntalar dependencia para poder operar base de datos
      #apt: name=python-pip
    #- name: instlar paquete
      apt:  name=python-mysqldb
      #pip: name=MySQL-python
      
    - name: cambio de contraseña de root
      mysql_user:
        login_user: root
        login_password: "{{ maria_contrasena }}"
        user: root
        check_implicit_admin: true
        password: "{{ maria_contrasena }}"
        host: localhost
        
    - name: creamos base de datos llamada wordpress
      mysql_db: name=wordpress state=present login_user=root login_password="{{ maria_contrasena }}"    
        
    - name: creamos usuario usuariwp y le damos los privilegios para la base de datos
      mysql_user:
        login_user: root
        login_password: "{{ maria_contrasena }}"
        name: usuariwp
        password: "{{ wp_contrasena }}"
        priv: 'wordpress.*:localhost'
        state: present
      
    - name: quitamos el usuario root remoto 
      mysql_user:
        check_implicit_admin: true
        login_user: root
        login_password: "{{ maria_contrasena }}"
        user: root
        host: "{{ ansible_fqdn }}"
        state: absent
