- hosts: madre.zavrel.cat
  gather_facts: true
  vars: 
    maria_contrasena: M1asix@1
    deploy_host: 192.168.0.32
 # vars_prompt:
  #- name: deploy_host
   # prompt: direcion de host para hacer la subida de base de datos?
    #private: no

  tasks:
  - name: guardar base de datos
    mysql_db:
     name: wordpress
     state: dump
     target: /tmp/backup.sql
     login_user: root
     login_password: "{{ maria_contrasena }}"
  - name: start the importing
    mysql_db:
     name: restoredb
     state: import
     target: /tmp/backup.sql
     login_host: "{{ deploy_host }}"
     login_user: root
     login_password: "{{ maria_contrasena }}"   
